import data from "@/data/shopFigma.json";
import { DEFAULT_LANG, type Lang } from "@/lib/i18n";
import { t } from "@/lib/t";
import type { Product } from "./products";
import type { Crop } from "./shop";

/** Figma box in frame px: [x, y, w, h] or, for texts, [x, y, w, h, lineHeight]. */
export type Box = number[];
export type FigmaLayout = {
  sig: string;
  frameH: number;
  gallery: Box[];
  title: Box;
  price: Box;
  desc: Box;
  options?: { box: Box; buttons: Box[] };
  cta: Box;
  line: Box;
  specs: Box;
  extraLabel?: Box;
  extraImg?: Box;
  suggest: Box;
  cards: Box;
};
type Entry = {
  name: string;
  priceFrom: number;
  title: string;
  detailPrice: string;
  cardPrice?: string;
  card?: Crop;
  gallery: Crop[];
  extra?: Crop & { label: string; w: number; h: number };
  layout?: FigmaLayout;
};
const entries = data.products as unknown as Record<string, Entry>;

/** Frame y where the gallery + info block ends. */
export const layoutBottom = (L: FigmaLayout) =>
  Math.max(...[...L.gallery, L.cta, L.specs, ...(L.extraImg ? [L.extraImg] : [])].map((b) => b[1] + b[3]));

// "265.000 VNĐ" / "265,000 VND"; 0 = price on request.
export const vnd = (n: number, lang: Lang = DEFAULT_LANG) =>
  n > 0 ? (lang === "en" ? `${n.toLocaleString("en-US")} VND` : `${n.toLocaleString("vi-VN")} VNĐ`) : t("Liên hệ", lang);

// Must match layoutSig() in scripts/figma-demo-shop.mjs.
const layoutSig = (p: Product) =>
  JSON.stringify([p.name, p.priceFrom, p.description, p.variants ?? [], p.specs ?? [], p.note ?? null, !!p.soldOut, p.image ?? null, p.thumbnails ?? []]);

/**
 * Figma-exact copy, image crops and desktop positions for a product (generated by scripts/figma-demo-shop.mjs).
 * Each piece is only used while the product still matches what the design was made for — once a name, price,
 * text or image is changed from /admin, the plain value / flow layout is used instead, so the design copy can
 * never show a stale price and absolutely positioned text can never overlap.
 */
export function figmaDisplay(p: Product) {
  const f = entries[p.id];
  const priced = f && f.priceFrom === p.priceFrom ? f : undefined;
  const images = [p.image, ...(p.thumbnails ?? [])].filter((s): s is string => Boolean(s));
  return {
    title: f?.name === p.name ? f.title : p.name,
    cardPrice: priced?.cardPrice ?? vnd(p.priceFrom),
    detailPrice: priced ? priced.detailPrice : p.priceFrom > 0 ? `${vnd(p.priceFrom)}/ ${p.unit}` : vnd(0),
    // guard f.card itself: a product with no image and no Figma entry would otherwise match undefined === undefined
    cardCrop: f?.card && f.card.src === p.image ? f.card : undefined,
    gallery: images.map((src, i) => (f?.gallery[i]?.src === src ? f.gallery[i] : { src })),
    extra: f?.extra,
    layout: f?.layout && !p.bundleItems?.length && f.layout.sig === layoutSig(p) ? f.layout : undefined,
  };
}

type ListingLayout = { ids: string[]; cards: number[][]; pager: number | null; frameH: number; tabColor: string | null };
const listings = data.listings as Record<string, ListingLayout>;

/** Figma card positions ([x, y] of each image) + pager y for a listing page, only while it shows exactly the Figma products. */
export function figmaListing(slug: string, page: number, ids: string[]) {
  const l = listings[`${slug}:${page}`];
  return l && l.ids.join() === ids.join() ? l : undefined;
}
