// GENERATED by scripts/gen-project-pages.mjs from the Figma "Thiết kế DEMO" frames — edit the script, not this file.
// Coordinates are Figma px on the 1280px frame, y measured from below the navbar (frame y - 51).
import type { FigPage } from "@/components/FigmaCanvas";

export const figmaPages: Record<string, FigPage> = {
 "kham-pha": {
  "h": 2189,
  "sections": [
   {
    "id": "671:455",
    "y": 0,
    "items": [
     {
      "k": "img",
      "id": "671:456",
      "x": -5,
      "y": 0,
      "w": 1343,
      "h": 514,
      "src": "/images/figma/4d2e77e4415d2a0140a31bc7d35c5f555c5f0d70.webp",
      "alt": "Dự án vui — Tíc Cơ",
      "crop": [
       [
        0.5758,
        0,
        0.0483
       ],
       [
        0,
        0.3279,
        0.1376
       ]
      ]
     },
     {
      "k": "text",
      "id": "671:457",
      "x": 59,
      "y": 69,
      "w": 605,
      "h": 111,
      "text": "dự án vui",
      "size": 135,
      "lh": 0.82,
      "ls": -0.08,
      "wt": 700,
      "align": "l",
      "color": "#f55f00",
      "tag": "h1",
      "nowrap": true
     },
     {
      "k": "text",
      "id": "671:458",
      "x": 247,
      "y": 183,
      "w": 320,
      "h": 48,
      "text": "về những dự án làm vì niềm vui,\nlàm với niềm vui của Tíc Cơ!",
      "size": 22,
      "lh": 1.09,
      "ls": -0.06,
      "wt": 600,
      "align": "r",
      "color": "#ffffff",
      "tag": "p",
      "nowrap": true
     }
    ]
   },
   {
    "id": "671:459",
    "y": 467,
    "items": [
     {
      "k": "box",
      "id": "671:460",
      "x": -5,
      "y": 467,
      "w": 1287,
      "h": 637,
      "bg": "linear-gradient(180deg,#e66107,#eb7b2e)"
     },
     {
      "k": "box",
      "id": "671:462",
      "x": 547,
      "y": 543,
      "w": 187,
      "h": 32,
      "bg": "#e5ff00"
     },
     {
      "k": "text",
      "id": "671:463",
      "x": 420,
      "y": 514,
      "w": 445,
      "h": 90,
      "text": "DỰ ÁN RIÊNG",
      "size": 25,
      "lh": 3.6,
      "ls": -0.04,
      "wt": 500,
      "align": "c",
      "color": "#55149f",
      "tag": "p",
      "nowrap": true,
      "bubble": "#e5ff00"
     },
     {
      "k": "card",
      "id": "671:464",
      "items": [
       {
        "k": "text",
        "id": "671:465",
        "x": 66,
        "y": 614,
        "w": 631,
        "h": 90,
        "text": "Người Việt Vận Động",
        "size": 50,
        "lh": 1.8,
        "ls": -0.07,
        "wt": 500,
        "align": "l",
        "color": "#ffffff",
        "tag": "h2",
        "nowrap": true
       },
       {
        "k": "text",
        "id": "671:466",
        "x": 667,
        "y": 637,
        "w": 559,
        "h": 27,
        "text": "dự án chung vui Lễ Quốc khánh 2025\nVận động không ngừng là vươn lên không dừng!",
        "size": 17,
        "lh": 1.06,
        "ls": -0.03,
        "wt": 300,
        "align": "r",
        "color": "#ffffff",
        "tag": "p"
       },
       {
        "k": "box",
        "id": "671:467",
        "x": 66,
        "y": 714,
        "w": 1156,
        "h": 1,
        "bg": "#ffffff",
        "kind": "line"
       }
      ],
      "href": "/kham-pha/nguoi-viet-van-dong"
     },
     {
      "k": "card",
      "id": "671:468",
      "items": [
       {
        "k": "text",
        "id": "671:469",
        "x": 66,
        "y": 724,
        "w": 631,
        "h": 90,
        "text": "Chúc Tết Nhau Thật Sự",
        "size": 50,
        "lh": 1.8,
        "ls": -0.07,
        "wt": 500,
        "align": "l",
        "color": "#ffffff",
        "tag": "h2",
        "nowrap": true
       },
       {
        "k": "text",
        "id": "671:470",
        "x": 667,
        "y": 759,
        "w": 559,
        "h": 36,
        "text": "dự án Tết Bính Ngọ 2026\nVì lời chúc là đầu câu chuyện!",
        "size": 17,
        "lh": 1.06,
        "ls": -0.03,
        "wt": 300,
        "align": "r",
        "color": "#ffffff",
        "tag": "p"
       },
       {
        "k": "box",
        "id": "671:471",
        "x": 70,
        "y": 829,
        "w": 1156,
        "h": 1,
        "bg": "#ffffff",
        "kind": "line"
       }
      ],
      "href": "/kham-pha/chuc-tet-nhau-that-su"
     },
     {
      "k": "card",
      "id": "671:472",
      "items": [
       {
        "k": "text",
        "id": "671:473",
        "x": 66,
        "y": 834,
        "w": 631,
        "h": 90,
        "text": "Làm Mới Đời Đi",
        "size": 50,
        "lh": 1.8,
        "ls": -0.07,
        "wt": 500,
        "align": "l",
        "color": "#ffffff",
        "tag": "h2",
        "nowrap": true
       },
       {
        "k": "text",
        "id": "671:474",
        "x": 667,
        "y": 864,
        "w": 559,
        "h": 55,
        "text": "dự án ảnh ọt vui vui\nchẳng nhân dịp gì!",
        "size": 17,
        "lh": 1,
        "ls": -0.03,
        "wt": 300,
        "align": "r",
        "color": "#ffffff",
        "tag": "p"
       },
       {
        "k": "box",
        "id": "671:475",
        "x": 70,
        "y": 939,
        "w": 1156,
        "h": 1,
        "bg": "#ffffff",
        "kind": "line"
       }
      ],
      "href": "/kham-pha/lam-moi-doi-di"
     },
     {
      "k": "card",
      "id": "671:476",
      "items": [
       {
        "k": "text",
        "id": "671:477",
        "x": 66,
        "y": 944,
        "w": 738,
        "h": 90,
        "text": "Mình Trong Nhà, Nhà Trong Nước",
        "size": 50,
        "lh": 1.8,
        "ls": -0.07,
        "wt": 500,
        "align": "l",
        "color": "#ffffff",
        "tag": "h2",
        "nowrap": true
       },
       {
        "k": "text",
        "id": "671:478",
        "x": 667,
        "y": 970,
        "w": 559,
        "h": 54,
        "text": "dự án chung vui Ngày Giải phòng miền Nam\nthống nhất đất nước 30/04/2024",
        "size": 17,
        "lh": 1.06,
        "ls": -0.03,
        "wt": 300,
        "align": "r",
        "color": "#ffffff",
        "tag": "p"
       }
      ],
      "href": "/kham-pha/minh-trong-nha-nha-trong-nuoc"
     }
    ],
    "bg": "linear-gradient(180deg,#e66107,#eb7b2e)",
    "anchor": "du-an-rieng"
   },
   {
    "id": "671:479",
    "y": 1104,
    "items": [
     {
      "k": "box",
      "id": "671:480",
      "x": -4,
      "y": 1104,
      "w": 1287,
      "h": 549,
      "bg": "linear-gradient(180deg,#53129e,#783ebb)"
     },
     {
      "k": "box",
      "id": "671:482",
      "x": 468,
      "y": 1187,
      "w": 348,
      "h": 32,
      "bg": "#e5ff00"
     },
     {
      "k": "text",
      "id": "671:483",
      "x": 422,
      "y": 1158,
      "w": 445,
      "h": 90,
      "text": "DỰ ÁN CHUNG TAY HỢP TÁC",
      "size": 25,
      "lh": 3.6,
      "ls": -0.04,
      "wt": 500,
      "align": "c",
      "color": "#c15106",
      "tag": "p",
      "nowrap": true,
      "bubble": "#e5ff00"
     },
     {
      "k": "card",
      "id": "671:484",
      "items": [
       {
        "k": "text",
        "id": "671:485",
        "x": 70,
        "y": 1273,
        "w": 631,
        "h": 112,
        "text": "Tíc Cơ x Freezedom:\nThu rồi Nghỉ đi!",
        "size": 50,
        "lh": 1.12,
        "ls": -0.07,
        "wt": 500,
        "align": "l",
        "color": "#ffffff",
        "tag": "h2",
        "nowrap": true
       },
       {
        "k": "text",
        "id": "671:486",
        "x": 663,
        "y": 1292,
        "w": 559,
        "h": 36,
        "text": "Tíc Cơ và Freezedom cùng bắt tay\nnghỉ ngơi vào những ngày thu 2025!",
        "size": 17,
        "lh": 1.06,
        "ls": -0.03,
        "wt": 300,
        "align": "r",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       },
       {
        "k": "box",
        "id": "671:487",
        "x": 70,
        "y": 1414,
        "w": 1156,
        "h": 1,
        "bg": "#ffffff",
        "kind": "line"
       }
      ],
      "href": "/kham-pha/freezedom-thu-roi-nghi-di"
     },
     {
      "k": "card",
      "id": "671:488",
      "items": [
       {
        "k": "text",
        "id": "671:489",
        "x": 70,
        "y": 1449,
        "w": 631,
        "h": 112,
        "text": "Tíc Cơ x Neenee:\nĐầu đội mũ, Chân vào đời",
        "size": 50,
        "lh": 1.12,
        "ls": -0.07,
        "wt": 500,
        "align": "l",
        "color": "#ffffff",
        "tag": "h2",
        "nowrap": true
       },
       {
        "k": "text",
        "id": "671:490",
        "x": 663,
        "y": 1513,
        "w": 559,
        "h": 36,
        "text": "dự án hợp tác sản phẩm\ngiữa Neenee và Tíc Cơ!",
        "size": 17,
        "lh": 1.06,
        "ls": -0.03,
        "wt": 300,
        "align": "r",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       }
      ],
      "href": "/kham-pha/neenee-dau-doi-mu-chan-vao-doi"
     }
    ],
    "bg": "linear-gradient(180deg,#53129e,#783ebb)",
    "anchor": "du-an-hop-tac"
   },
   {
    "id": "671:491",
    "y": 1653,
    "items": [
     {
      "k": "box",
      "id": "671:492",
      "x": 0,
      "y": 1653,
      "w": 1287,
      "h": 536,
      "bg": "linear-gradient(180deg,#e66107,#eb7b2e)"
     },
     {
      "k": "box",
      "id": "671:494",
      "x": 587,
      "y": 1720,
      "w": 115,
      "h": 32,
      "bg": "#e5ff00"
     },
     {
      "k": "text",
      "id": "671:495",
      "x": 422,
      "y": 1691,
      "w": 445,
      "h": 90,
      "text": "SỰ KIỆN",
      "size": 25,
      "lh": 3.6,
      "ls": -0.04,
      "wt": 500,
      "align": "c",
      "color": "#53129e",
      "tag": "p",
      "nowrap": true,
      "bubble": "#e5ff00"
     },
     {
      "k": "card",
      "id": "671:496",
      "items": [
       {
        "k": "text",
        "id": "671:497",
        "x": 70,
        "y": 1801,
        "w": 697,
        "h": 112,
        "text": "Tíc Cơ tại Khu vực trải nghiệm\nLễ hội Độc lập",
        "size": 50,
        "lh": 1.12,
        "ls": -0.07,
        "wt": 500,
        "align": "l",
        "color": "#ffffff",
        "tag": "h2",
        "nowrap": true
       },
       {
        "k": "text",
        "id": "671:498",
        "x": 730,
        "y": 1818,
        "w": 496,
        "h": 54,
        "text": "“Lễ Hội Độc Lập - 80 Năm Tự Hào Việt Nam” là sự kiện văn hóa, nghệ thuật do UBND TP Hà Nội, Sở Văn hóa - Thể thao phối hợp cùng Trung ương Hội Sinh viên Việt Nam tổ chức",
        "size": 17,
        "lh": 1.06,
        "ls": -0.03,
        "wt": 300,
        "align": "r",
        "color": "#ffffff",
        "tag": "p"
       },
       {
        "k": "box",
        "id": "671:499",
        "x": 70,
        "y": 1952,
        "w": 1156,
        "h": 1,
        "bg": "#ffffff",
        "kind": "line"
       }
      ],
      "href": "/kham-pha/nguoi-viet-van-dong#le-hoi-doc-lap"
     },
     {
      "k": "card",
      "id": "671:500",
      "items": [
       {
        "k": "text",
        "id": "671:501",
        "x": 66,
        "y": 1991,
        "w": 697,
        "h": 112,
        "text": "Pop-up Event\nThu rồi nghỉ đi",
        "size": 50,
        "lh": 1.12,
        "ls": -0.07,
        "wt": 500,
        "align": "l",
        "color": "#ffffff",
        "tag": "h2",
        "nowrap": true
       },
       {
        "k": "text",
        "id": "671:502",
        "x": 663,
        "y": 2001,
        "w": 559,
        "h": 36,
        "text": "Một không gian gặp gỡ, lấy cái cớ để bạn nghỉ đi,\nhưởng trời thu và chẳng làm gì nhiều",
        "size": 17,
        "lh": 1.06,
        "ls": -0.03,
        "wt": 300,
        "align": "r",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       }
      ],
      "href": "/kham-pha/freezedom-thu-roi-nghi-di#pop-up-event"
     }
    ],
    "bg": "linear-gradient(180deg,#e66107,#eb7b2e)",
    "anchor": "su-kien"
   }
  ]
 },
 "nguoi-viet-van-dong": {
  "h": 3728,
  "sections": [
   {
    "id": "671:530",
    "y": 0,
    "items": [
     {
      "k": "box",
      "id": "671:531",
      "x": 0,
      "y": 0,
      "w": 1280,
      "h": 524,
      "bg": "#b51515"
     },
     {
      "k": "text",
      "id": "671:532",
      "x": 62,
      "y": 151,
      "w": 768,
      "h": 274,
      "text": "Người Việt\nVận Động",
      "size": 135,
      "lh": 1.01,
      "ls": -0.08,
      "wt": 400,
      "align": "l",
      "color": "#ffffff",
      "tag": "h1",
      "nowrap": true
     },
     {
      "k": "text",
      "id": "671:533",
      "x": 890,
      "y": 369,
      "w": 327,
      "h": 56,
      "text": "Dự án chung vui\nLễ Quốc khánh 2025",
      "size": 24,
      "lh": 1.17,
      "ls": -0.05,
      "wt": 400,
      "align": "r",
      "color": "#ffffff",
      "tag": "p",
      "nowrap": true
     }
    ],
    "bg": "#b51515"
   },
   {
    "id": "671:534",
    "y": 524,
    "items": [
     {
      "k": "img",
      "id": "671:534",
      "x": -7,
      "y": 524,
      "w": 1293,
      "h": 482,
      "src": "/images/figma/1a58070a24240b258f6fbd5232c4c125419ca6ec.webp",
      "alt": "Người Việt Vận Động — Tíc Cơ",
      "crop": [
       [
        1,
        0,
        0
       ],
       [
        0,
        0.2797,
        0.3918
       ]
      ]
     }
    ]
   },
   {
    "id": "671:535",
    "y": 1006,
    "items": [
     {
      "k": "box",
      "id": "671:536",
      "x": 0,
      "y": 1006,
      "w": 1280,
      "h": 1297,
      "bg": "#b51515"
     },
     {
      "k": "card",
      "id": "671:537",
      "items": [
       {
        "k": "text",
        "id": "671:538",
        "x": 62,
        "y": 1065,
        "w": 389,
        "h": 80,
        "text": "Vận động không ngừng là vươn lên không dừng!",
        "size": 36,
        "lh": 1.11,
        "ls": -0.05,
        "wt": 400,
        "align": "l",
        "color": "#ffffff",
        "tag": "h2"
       },
       {
        "k": "img",
        "id": "668:27",
        "x": 864,
        "y": 1065,
        "w": 353,
        "h": 442,
        "src": "/images/figma/1542c5e6ab7285e28e836b2188f14488889b8553.webp",
        "alt": "Vận động không ngừng là vươn lên không dừng!",
        "crop": [
         [
          0.6148,
          0,
          0.3597
         ],
         [
          0,
          0.5768,
          0.1958
         ]
        ]
       },
       {
        "k": "text",
        "id": "671:540",
        "x": 62,
        "y": 1291,
        "w": 593,
        "h": 264,
        "text": "Sự sống là nhờ vận động, phát triển là nhờ vận động, người Việt vận động để đất nước không ngừng vươn lên!\nBởi vận động là chuyện cả đời, người Việt vận động từ lịch sử tới hiện tại, từ thời cha chú đến thời người trẻ, những lớp người nối tiếp và kế thừa, những câu chuyện đời sống hình thành để dấu ấn dân tộc được thành hình.\n\nTháng Tám cờ và hoa, Tíc Cơ phấn khởi được cùng bạn kể những câu chuyện về đất nước độc lập, về sự chuyển động âm thầm trong đời sống, về tinh thần vươn lên sống chất của mọi người dân Việt Nam!",
        "size": 18,
        "lh": 1.33,
        "ls": -0.05,
        "wt": 300,
        "align": "l",
        "color": "#ffffff",
        "tag": "p"
       }
      ]
     },
     {
      "k": "text",
      "id": "671:542",
      "x": 62,
      "y": 1654,
      "w": 751,
      "h": 120,
      "text": "Kể bạn nghe về những sự sống đang vận động mỗi ngày, và những người Việt đang không ngừng vận động vì một Việt Nam vươn lên.",
      "size": 36,
      "lh": 1.11,
      "ls": -0.05,
      "wt": 400,
      "align": "l",
      "color": "#ffffff",
      "tag": "h2"
     },
     {
      "k": "card",
      "id": "671:543",
      "items": [
       {
        "k": "img",
        "id": "671:544",
        "x": 223,
        "y": 1827,
        "w": 263,
        "h": 325,
        "src": "/images/figma/48427e553bc4a7b24bf02758465b387ca21d4b8a.webp",
        "alt": "Đọc thêm về người Việt U80 vươn lên"
       },
       {
        "k": "text",
        "id": "671:545",
        "x": 256,
        "y": 2177,
        "w": 198,
        "h": 32,
        "text": "Đọc thêm về\nngười Việt U80 vươn lên",
        "size": 14,
        "lh": 1.14,
        "ls": -0.05,
        "wt": 300,
        "align": "c",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       }
      ]
     },
     {
      "k": "card",
      "id": "671:546",
      "items": [
       {
        "k": "img",
        "id": "671:547",
        "x": 508,
        "y": 1827,
        "w": 264,
        "h": 325,
        "src": "/images/figma/7b1d70d19d6a096ee34dcafb980a59428f4b19f7.webp",
        "alt": "Đọc thêm về người Việt U30 vươn lên"
       },
       {
        "k": "text",
        "id": "671:548",
        "x": 541,
        "y": 2177,
        "w": 198,
        "h": 32,
        "text": "Đọc thêm về\nngười Việt U30 vươn lên",
        "size": 14,
        "lh": 1.14,
        "ls": -0.05,
        "wt": 300,
        "align": "c",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       }
      ]
     },
     {
      "k": "card",
      "id": "671:549",
      "items": [
       {
        "k": "img",
        "id": "671:550",
        "x": 794,
        "y": 1827,
        "w": 263,
        "h": 325,
        "src": "/images/figma/ad82920ad986fc8e2129f79a5d9c0e9b80d4759d.webp",
        "alt": "Đọc thêm về người Việt U10 vươn lên"
       },
       {
        "k": "text",
        "id": "671:551",
        "x": 827,
        "y": 2177,
        "w": 198,
        "h": 32,
        "text": "Đọc thêm về\nngười Việt U10 vươn lên",
        "size": 14,
        "lh": 1.14,
        "ls": -0.05,
        "wt": 300,
        "align": "c",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       }
      ]
     }
    ],
    "bg": "#b51515"
   },
   {
    "id": "671:552",
    "y": 2303,
    "items": [
     {
      "k": "box",
      "id": "671:553",
      "x": 0,
      "y": 2303,
      "w": 1280,
      "h": 1425,
      "bg": "#2c5242"
     },
     {
      "k": "card",
      "id": "671:554",
      "items": [
       {
        "k": "text",
        "id": "671:555",
        "x": 62,
        "y": 2389,
        "w": 693,
        "h": 160,
        "text": "Merchandise đặc biệt\nLễ Quốc khánh 2025\n- Quạt Người Việt Vận Động",
        "size": 36,
        "lh": 1.11,
        "ls": -0.05,
        "wt": 400,
        "align": "l",
        "color": "#ffffff",
        "tag": "h2"
       },
       {
        "k": "img",
        "id": "671:556",
        "x": 541,
        "y": 2376,
        "w": 308,
        "h": 388,
        "src": "/images/figma/ee4d09678fea0a86f17881541f07849441b481a9.webp",
        "alt": "Merchandise đặc biệt Lễ Quốc khánh 2025 - Quạt Người Việt Vận Động",
        "crop": [
         [
          0.9993,
          0,
          0.0004
         ],
         [
          0,
          0.9448,
          0.0552
         ]
        ]
       },
       {
        "k": "text",
        "id": "671:557",
        "x": 255,
        "y": 2860,
        "w": 593,
        "h": 75,
        "text": "Hai mặt quạt một tinh thần\nbởi vì quạt không dừng là vận động không ngừng,\nngười Việt vận động không ngừng là đất nước vươn lên không dừng!",
        "size": 18,
        "lh": 1.39,
        "ls": -0.05,
        "wt": 300,
        "align": "r",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       }
      ]
     },
     {
      "k": "text",
      "id": "671:560",
      "x": 62,
      "y": 3074,
      "w": 693,
      "h": 80,
      "text": "Gian hàng trải nghiệm\nTíc Cơ tại Lễ hội Độc lập",
      "size": 36,
      "lh": 1.11,
      "ls": -0.05,
      "wt": 400,
      "align": "l",
      "color": "#ffffff",
      "tag": "h2",
      "anchor": "le-hoi-doc-lap",
      "nowrap": true
     },
     {
      "k": "text",
      "id": "671:561",
      "x": 624,
      "y": 3085,
      "w": 593,
      "h": 225,
      "text": "“Lễ Hội Độc Lập - 80 Năm Tự Hào Việt Nam” là sự kiện văn hóa, nghệ thuật do UBND TP Hà Nội, Sở Văn hóa - Thể thao phối hợp cùng Trung ương Hội Sinh viên Việt Nam tổ chức, nhân dịp kỷ niệm 80 năm Cách mạng Tháng Tám và Quốc khánh 2/9 (A80).\n\nTiếp vào dòng chảy vận động của cả đất nước, góp một phần nhỏ vào sắc đỏ của Thủ đô, Tíc Cơ mở gian hàng nhỏ, rủ bạn tới chơi tại gian hàng triển lãm Lễ Hội Độc Lập 2025.",
      "size": 18,
      "lh": 1.39,
      "ls": -0.05,
      "wt": 300,
      "align": "r",
      "color": "#ffffff",
      "tag": "p"
     },
     {
      "k": "img",
      "id": "671:562",
      "x": 125,
      "y": 3325,
      "w": 210,
      "h": 263,
      "src": "/images/figma/0280fe4f6963ebdf3e60bea69168aa80a99bd729.webp",
      "alt": "Người Việt Vận Động — Tíc Cơ"
     },
     {
      "k": "img",
      "id": "671:563",
      "x": 354,
      "y": 3326,
      "w": 209,
      "h": 262,
      "src": "/images/figma/71781758c840da4d3dc44869e81eb326e0ba1d72.webp",
      "alt": "Người Việt Vận Động — Tíc Cơ",
      "crop": [
       [
        0.8128,
        0,
        0.0934
       ],
       [
        0,
        0.5732,
        0.3603
       ]
      ]
     },
     {
      "k": "img",
      "id": "671:564",
      "x": 582,
      "y": 3326,
      "w": 350,
      "h": 262,
      "src": "/images/figma/1277fc9763149f8eda7f1002f4b1ede1f6a08b42.webp",
      "alt": "Người Việt Vận Động — Tíc Cơ",
      "crop": [
       [
        0.7006,
        0,
        0.0979
       ],
       [
        0,
        0.6993,
        0.2005
       ]
      ]
     },
     {
      "k": "img",
      "id": "671:565",
      "x": 951,
      "y": 3325,
      "w": 203,
      "h": 263,
      "src": "/images/figma/c70b5990b5fdbea2936ade9df5bbb6ca7f306aee.webp",
      "alt": "Người Việt Vận Động — Tíc Cơ",
      "crop": [
       [
        0.7368,
        0,
        0.1176
       ],
       [
        0,
        0.7176,
        0
       ]
      ]
     }
    ],
    "bg": "#2c5242"
   }
  ]
 },
 "chuc-tet-nhau-that-su": {
  "h": 2914,
  "sections": [
   {
    "id": "671:593",
    "y": 0,
    "items": [
     {
      "k": "box",
      "id": "671:594",
      "x": 0,
      "y": 0,
      "w": 1280,
      "h": 756,
      "bg": "#fea0c9"
     },
     {
      "k": "text",
      "id": "671:595",
      "x": 65,
      "y": 111,
      "w": 1091,
      "h": 274,
      "text": "Chúc Tết Nhau\nThật Sự",
      "size": 135,
      "lh": 1.01,
      "ls": -0.08,
      "wt": 400,
      "align": "l",
      "color": "#b00808",
      "tag": "h1",
      "nowrap": true
     },
     {
      "k": "text",
      "id": "671:596",
      "x": 974,
      "y": 178,
      "w": 197,
      "h": 56,
      "text": "Dự án Tết\nBính Ngọ 2026",
      "size": 24,
      "lh": 1.17,
      "ls": -0.05,
      "wt": 400,
      "align": "r",
      "color": "#b00808",
      "tag": "p",
      "nowrap": true
     },
     {
      "k": "box",
      "id": "668:123",
      "x": -81,
      "y": 454,
      "w": 1440,
      "h": 576,
      "bg": "linear-gradient(180deg,#b00808,#a51b1b)",
      "radius": "50%"
     },
     {
      "k": "img",
      "id": "668:38",
      "x": 485,
      "y": 263,
      "w": 445,
      "h": 431,
      "src": "/images/figma/39b087b38d83c8208cd5f14b33490b3b8f6db31f.webp",
      "alt": "Chúc Tết Nhau Thật Sự — Tíc Cơ",
      "crop": [
       [
        0.6053,
        0,
        0.1798
       ],
       [
        0,
        0.4399,
        0.1938
       ]
      ]
     },
     {
      "k": "text",
      "id": "668:35",
      "x": 233,
      "y": 432,
      "w": 378,
      "h": 114,
      "text": "Bước vào nhà gia chủ\nchúc Tết thì nói gì?\nCâu đầu tiên trong năm mới\nngười ta nói với nhau là gì?",
      "size": 20,
      "lh": 1.15,
      "ls": -0.05,
      "wt": 400,
      "align": "l",
      "color": "#ffffff",
      "tag": "p",
      "mark": "#b00808"
     },
     {
      "k": "text",
      "id": "668:40",
      "x": 801,
      "y": 287,
      "w": 365,
      "h": 114,
      "text": "Năm mới chúc ông sức khoẻ!\nNăm mới chúc bác\nthành công phát đạt!\nChúc cả nhà bình an hạnh phúc!",
      "size": 20,
      "lh": 1.15,
      "ls": -0.05,
      "wt": 400,
      "align": "r",
      "color": "#ffffff",
      "tag": "p",
      "mark": "#b00808"
     }
    ],
    "bg": "#fea0c9"
   },
   {
    "id": "668:67",
    "y": 756,
    "items": [
     {
      "k": "img",
      "id": "668:30",
      "x": 0,
      "y": 756,
      "w": 1280,
      "h": 482,
      "src": "/images/figma/898b8d47249a561987e9cb18c24025ffdd4dbffd.webp",
      "alt": "Chúc Tết Nhau Thật Sự — Tíc Cơ",
      "crop": [
       [
        0.1692,
        0,
        0.427
       ],
       [
        0,
        0.668,
        0.1691
       ]
      ],
      "rot": 90
     },
     {
      "k": "text",
      "id": "668:42",
      "x": 61,
      "y": 812,
      "w": 344,
      "h": 78,
      "text": "Vì lời chúc là\n đầu câu chuyện!",
      "size": 36,
      "lh": 1.08,
      "ls": -0.08,
      "wt": 400,
      "align": "l",
      "color": "#fea0c9",
      "tag": "h2",
      "nowrap": true
     }
    ]
   },
   {
    "id": "863:84",
    "y": 1238,
    "items": [
     {
      "k": "box",
      "id": "668:70",
      "x": -1,
      "y": 1238,
      "w": 1280,
      "h": 1713,
      "bg": "#fea0c9"
     },
     {
      "k": "text",
      "id": "668:72",
      "x": 343,
      "y": 1334,
      "w": 593,
      "h": 173,
      "text": "Người Việt chúc Tết nhau bằng mấy câu chúc rất quen thuộc: chúc sức khoẻ, chúc hạnh phúc, chúc phát đạt...\nGiá trị của Tết nằm ở chỗ, dù lời chúc bật ra khỏi miệng theo phản xạ, là thuận miệng, là câu là quen là ngắn, vẫn chân thành và xuất phát từ tình cảm quý mến thật sự.\n\nBính Ngọ 2026, Tíc Cơ gửi bạn mấy câu chúc đời thường mà không hề qua loa sáo rỗng!",
      "size": 18,
      "lh": 1.33,
      "ls": -0.05,
      "wt": 300,
      "align": "j",
      "color": "#ffffff",
      "tag": "p",
      "mark": "#b00808"
     },
     {
      "k": "text",
      "id": "668:120",
      "x": 409,
      "y": 1610,
      "w": 462,
      "h": 88,
      "text": "Bộ sưu tập 04 sản phẩm\nmùa Tết 2026",
      "size": 42,
      "lh": 1.05,
      "ls": -0.05,
      "wt": 500,
      "align": "c",
      "color": "#b00808",
      "tag": "h2",
      "nowrap": true
     },
     {
      "k": "text",
      "id": "668:122",
      "x": 413,
      "y": 1761,
      "w": 454,
      "h": 88,
      "text": "với tinh thần vận động toàn dân chúc Tết nhau thật sự, chúng tôi đơn giản là muốn nói: mấy câu chúc\nthuận miệng ấy vốn không hề qua loa,\nkhi người ta nói ra từ sự chân thành và quý mến!",
      "size": 18,
      "lh": 1.22,
      "ls": -0.05,
      "wt": 300,
      "align": "c",
      "color": "#000000",
      "tag": "p"
     },
     {
      "k": "box",
      "id": "668:124",
      "x": 629,
      "y": 1719,
      "w": 21,
      "h": 21,
      "bg": "#b00808",
      "radius": "50%",
      "kind": "dot"
     },
     {
      "k": "box",
      "id": "668:125",
      "x": 629,
      "y": 1870,
      "w": 21,
      "h": 21,
      "bg": "#b00808",
      "radius": "50%",
      "kind": "dot"
     },
     {
      "k": "card",
      "id": "863:71",
      "items": [
       {
        "k": "img",
        "id": "863:57",
        "x": 301,
        "y": 1930,
        "w": 277,
        "h": 346,
        "src": "/images/figma/e3bb3efef65e3164986172913836d0c9834070d4.webp",
        "alt": "GILE YÊN TÂM",
        "crop": [
         [
          0.834,
          0,
          0.0545
         ],
         [
          0,
          0.8335,
          0.1473
         ]
        ]
       },
       {
        "k": "text",
        "id": "863:65",
        "x": 353,
        "y": 2295,
        "w": 174,
        "h": 20,
        "text": "GILE YÊN TÂM",
        "size": 20,
        "lh": 1.05,
        "ls": -0.04,
        "wt": 400,
        "align": "c",
        "color": "#323133",
        "tag": "p",
        "nowrap": true
       },
       {
        "k": "text",
        "id": "863:66",
        "x": 314,
        "y": 2318,
        "w": 252,
        "h": 20,
        "text": "Lời ít ý nhiều, chúc bạn yên ở tâm",
        "size": 16,
        "lh": 1.31,
        "ls": -0.04,
        "wt": 300,
        "align": "c",
        "color": "#000000",
        "tag": "p",
        "nowrap": true
       }
      ],
      "href": "/san-pham/gile-yen-tam"
     },
     {
      "k": "card",
      "id": "863:72",
      "items": [
       {
        "k": "img",
        "id": "863:63",
        "x": 701,
        "y": 1929,
        "w": 277,
        "h": 347,
        "src": "/images/figma/dd188dc98b9d208a4fc505d57d56485a3ce84cd7.webp",
        "alt": "THẦN CHÚ NĂM MỚI 2026"
       },
       {
        "k": "text",
        "id": "863:68",
        "x": 717,
        "y": 2295,
        "w": 245,
        "h": 20,
        "text": "THẦN CHÚ NĂM MỚI 2026",
        "size": 20,
        "lh": 1.05,
        "ls": -0.04,
        "wt": 400,
        "align": "c",
        "color": "#323133",
        "tag": "p",
        "nowrap": true
       },
       {
        "k": "text",
        "id": "863:69",
        "x": 714,
        "y": 2316,
        "w": 264,
        "h": 20,
        "text": "Lịch mini 12 tháng 12 câu chúc quen, chúc qua năm qua tháng",
        "size": 16,
        "lh": 1.31,
        "ls": -0.04,
        "wt": 300,
        "align": "c",
        "color": "#000000",
        "tag": "p",
        "nowrap": true
       }
      ],
      "href": "/san-pham/than-chu-nam-moi-2026"
     },
     {
      "k": "card",
      "id": "863:76",
      "items": [
       {
        "k": "img",
        "id": "863:61",
        "x": 301,
        "y": 2401,
        "w": 277,
        "h": 347,
        "src": "/images/figma/9c336a85ed4630d98983e404c3a7eec75f23d018.webp",
        "alt": "SET STICKER CHÚC NHAU THẬT SỰ",
        "crop": [
         [
          0.6651,
          0,
          0.1671
         ],
         [
          0,
          0.5556,
          0.2803
         ]
        ]
       },
       {
        "k": "text",
        "id": "863:73",
        "x": 285,
        "y": 2763,
        "w": 310,
        "h": 20,
        "text": "SET STICKER CHÚC NHAU THẬT SỰ",
        "size": 20,
        "lh": 1.05,
        "ls": -0.04,
        "wt": 400,
        "align": "c",
        "color": "#323133",
        "tag": "p",
        "nowrap": true
       },
       {
        "k": "text",
        "id": "863:74",
        "x": 314,
        "y": 2785,
        "w": 252,
        "h": 20,
        "text": "8 tấm stickers, 8 câu chúc thật lòng",
        "size": 16,
        "lh": 1.31,
        "ls": -0.04,
        "wt": 300,
        "align": "c",
        "color": "#000000",
        "tag": "p",
        "nowrap": true
       }
      ],
      "href": "/san-pham/sticker-09-chuc-nhau-that-su"
     },
     {
      "k": "card",
      "id": "863:80",
      "items": [
       {
        "k": "img",
        "id": "863:59",
        "x": 701,
        "y": 2401,
        "w": 277,
        "h": 346,
        "src": "/images/figma/5d96f6fdc6bd5cbc6273918d544bbfc6bebd69c6.webp",
        "alt": "LÌ XÌ CHÚC TẾT NHAU THẬT SỰ",
        "crop": [
         [
          0.885,
          0,
          0.0571
         ],
         [
          0,
          0.8851,
          0.0571
         ]
        ]
       },
       {
        "k": "text",
        "id": "863:77",
        "x": 691,
        "y": 2763,
        "w": 310,
        "h": 20,
        "text": "LÌ XÌ CHÚC TẾT NHAU THẬT SỰ",
        "size": 20,
        "lh": 1.05,
        "ls": -0.04,
        "wt": 400,
        "align": "c",
        "color": "#323133",
        "tag": "p",
        "nowrap": true
       },
       {
        "k": "text",
        "id": "863:78",
        "x": 720,
        "y": 2785,
        "w": 252,
        "h": 20,
        "text": "6 bao lì xì, 6 câu chúc quen thủ thỉ",
        "size": 16,
        "lh": 1.31,
        "ls": -0.04,
        "wt": 300,
        "align": "c",
        "color": "#000000",
        "tag": "p",
        "nowrap": true
       }
      ],
      "href": "/san-pham/li-xi-2026"
     }
    ],
    "bg": "#fea0c9"
   }
  ]
 },
 "lam-moi-doi-di": {
  "h": 3133,
  "sections": [
   {
    "id": "682:37",
    "y": 0,
    "items": [
     {
      "k": "box",
      "id": "682:38",
      "x": 0,
      "y": 0,
      "w": 1280,
      "h": 524,
      "bg": "#0017ae"
     },
     {
      "k": "text",
      "id": "682:39",
      "x": 62,
      "y": 151,
      "w": 768,
      "h": 274,
      "text": "Làm Mới\nĐời Đi",
      "size": 135,
      "lh": 1.01,
      "ls": -0.08,
      "wt": 400,
      "align": "l",
      "color": "#ffffff",
      "tag": "h1",
      "nowrap": true
     },
     {
      "k": "text",
      "id": "682:40",
      "x": 890,
      "y": 369,
      "w": 327,
      "h": 56,
      "text": "Dự án ảnh ọt vui vui\nchẳng nhân dịp gì!",
      "size": 24,
      "lh": 1.17,
      "ls": -0.05,
      "wt": 400,
      "align": "r",
      "color": "#ffffff",
      "tag": "p",
      "nowrap": true
     }
    ],
    "bg": "#0017ae"
   },
   {
    "id": "682:82",
    "y": 524,
    "items": [
     {
      "k": "img",
      "id": "682:82",
      "x": 2,
      "y": 524,
      "w": 1284,
      "h": 417,
      "src": "/images/figma/cf56a704213cedc9874854453062f07a3f7db02d.webp",
      "alt": "Làm Mới Đời Đi — Tíc Cơ",
      "crop": [
       [
        0.5135,
        0,
        0
       ],
       [
        0,
        0.9999,
        0
       ]
      ]
     }
    ]
   },
   {
    "id": "682:112",
    "y": 941,
    "items": [
     {
      "k": "box",
      "id": "682:84",
      "x": 0,
      "y": 941,
      "w": 1280,
      "h": 1738,
      "bg": "#0017ae"
     },
     {
      "k": "text",
      "id": "682:86",
      "x": 390,
      "y": 1078,
      "w": 507,
      "h": 160,
      "text": "Ngày này không giống ngày kia, đời mà cứ lặp đi lặp lại\nthì chẳng vui!",
      "size": 36,
      "lh": 1.11,
      "ls": -0.05,
      "wt": 400,
      "align": "l",
      "color": "#ffffff",
      "tag": "h2"
     },
     {
      "k": "text",
      "id": "682:88",
      "x": 390,
      "y": 1246,
      "w": 476,
      "h": 72,
      "text": "Cái giỏ, cái láp, cái nón, làm mới mọi điều quanh mình thêm hay ho và màu sắc. Tíc Cơ ở đây, chúng tôi tô màu cho những điều tưởng chừng như là bình thường!",
      "size": 18,
      "lh": 1.33,
      "ls": -0.05,
      "wt": 300,
      "align": "l",
      "color": "#ffffff",
      "tag": "p"
     },
     {
      "k": "text",
      "id": "682:90",
      "x": 390,
      "y": 1455,
      "w": 507,
      "h": 200,
      "text": "Những thứ đời thường đâu có nhàm chán, chúng tôi len lỏi vào đời sống và mang đến màu sắc cho cuộc đời với những sản phẩm tiêu dùng sáng tạo!",
      "size": 36,
      "lh": 1.11,
      "ls": -0.05,
      "wt": 400,
      "align": "l",
      "color": "#ffffff",
      "tag": "h2"
     },
     {
      "k": "img",
      "id": "682:100",
      "x": 779,
      "y": 2267,
      "w": 262,
      "h": 262,
      "src": "/images/figma/f0716ebc1a5904cac6eebf5ed7422104df40c453.webp",
      "alt": "Làm Mới Đời Đi — Tíc Cơ"
     },
     {
      "k": "img",
      "id": "682:95",
      "x": 509,
      "y": 2267,
      "w": 262,
      "h": 262,
      "src": "/images/figma/2de4902855a664b74e2504cc9a1a479da29246d6.webp",
      "alt": "Làm Mới Đời Đi — Tíc Cơ"
     },
     {
      "k": "img",
      "id": "682:93",
      "x": 239,
      "y": 2267,
      "w": 262,
      "h": 262,
      "src": "/images/figma/befdda82d0ca5f93f53235e149d547fd50c25649.webp",
      "alt": "Làm Mới Đời Đi — Tíc Cơ"
     },
     {
      "k": "img",
      "id": "682:96",
      "x": 779,
      "y": 1994,
      "w": 262,
      "h": 262,
      "src": "/images/figma/6d1746c5eeccef335009fe17e16de626c7fd82ac.webp",
      "alt": "Làm Mới Đời Đi — Tíc Cơ"
     },
     {
      "k": "img",
      "id": "682:99",
      "x": 509,
      "y": 1995,
      "w": 262,
      "h": 262,
      "src": "/images/figma/5959f2ecd71ec3145f15a27650de17c60f1ea287.webp",
      "alt": "Làm Mới Đời Đi — Tíc Cơ"
     },
     {
      "k": "img",
      "id": "682:94",
      "x": 239,
      "y": 1994,
      "w": 262,
      "h": 262,
      "src": "/images/figma/ab112a16256f7ce45d07f60f3f80eac75cf20beb.webp",
      "alt": "Làm Mới Đời Đi — Tíc Cơ"
     },
     {
      "k": "img",
      "id": "682:92",
      "x": 779,
      "y": 1721,
      "w": 262,
      "h": 262,
      "src": "/images/figma/5d894a693cf59abafeaf704b316c9bdc8d60c80d.webp",
      "alt": "Làm Mới Đời Đi — Tíc Cơ"
     },
     {
      "k": "img",
      "id": "682:97",
      "x": 509,
      "y": 1724,
      "w": 262,
      "h": 262,
      "src": "/images/figma/353f5093808339db299223c3da70ba3ce82e83ec.webp",
      "alt": "Làm Mới Đời Đi — Tíc Cơ"
     },
     {
      "k": "img",
      "id": "682:98",
      "x": 239,
      "y": 1724,
      "w": 262,
      "h": 262,
      "src": "/images/figma/d4d3f1b1b54e0300e1ae1144260fdcea7e0dda58.webp",
      "alt": "Làm Mới Đời Đi — Tíc Cơ"
     },
     {
      "k": "img",
      "id": "682:101",
      "x": 0,
      "y": 2691,
      "w": 1289,
      "h": 442,
      "src": "/images/figma/cf56a704213cedc9874854453062f07a3f7db02d.webp",
      "alt": "Làm Mới Đời Đi — Tíc Cơ",
      "crop": [
       [
        0.486,
        0,
        0.514
       ],
       [
        0,
        1,
        0
       ]
      ]
     }
    ],
    "bg": "#0017ae"
   }
  ]
 },
 "minh-trong-nha-nha-trong-nuoc": {
  "h": 2789,
  "sections": [
   {
    "id": "682:134",
    "y": 0,
    "items": [
     {
      "k": "box",
      "id": "682:135",
      "x": 0,
      "y": 0,
      "w": 1280,
      "h": 524,
      "bg": "#b51515"
     },
     {
      "k": "text",
      "id": "682:136",
      "x": 62,
      "y": 223,
      "w": 772,
      "h": 202,
      "text": "Mình Trong Nhà\nNhà Trong Nước",
      "size": 100,
      "lh": 1.01,
      "ls": -0.08,
      "wt": 400,
      "align": "l",
      "color": "#ffffff",
      "tag": "h1",
      "nowrap": true
     },
     {
      "k": "text",
      "id": "682:137",
      "x": 834,
      "y": 239,
      "w": 385,
      "h": 84,
      "text": "Dự án chung vui\nkỷ niệm Ngày Giải phóng miền Nam Thống nhất đất nước",
      "size": 24,
      "lh": 1.17,
      "ls": -0.05,
      "wt": 400,
      "align": "r",
      "color": "#ffffff",
      "tag": "p"
     },
     {
      "k": "text",
      "id": "694:27",
      "x": 834,
      "y": 388,
      "w": 385,
      "h": 28,
      "text": "30/04/2024",
      "size": 18,
      "lh": 1.56,
      "ls": -0.05,
      "wt": 400,
      "align": "r",
      "color": "#ffffff",
      "tag": "p",
      "nowrap": true
     }
    ],
    "bg": "#b51515"
   },
   {
    "id": "692:191",
    "y": 524,
    "items": [
     {
      "k": "img",
      "id": "692:191",
      "x": 0,
      "y": 524,
      "w": 1280,
      "h": 788,
      "src": "/images/figma/ab19359990d2892e41b2099055d52cd59ce8b508.webp",
      "alt": "Mình Trong Nhà, Nhà Trong Nước — Tíc Cơ",
      "crop": [
       [
        1,
        0,
        0
       ],
       [
        0,
        0.3464,
        0.4051
       ]
      ]
     }
    ]
   },
   {
    "id": "735:177",
    "y": 1176,
    "items": [
     {
      "k": "box",
      "id": "685:167",
      "x": 0,
      "y": 1176,
      "w": 1280,
      "h": 1613,
      "bg": "#b51515"
     },
     {
      "k": "card",
      "id": "735:172",
      "items": [
       {
        "k": "text",
        "id": "685:169",
        "x": 448,
        "y": 1267,
        "w": 384,
        "h": 84,
        "text": "Tay ông đặt cạnh tay cháu\nThế hệ trước đi cạnh thế hệ sau\nMàu máu đỏ đi liền với hình sao vàng",
        "size": 24,
        "lh": 1.17,
        "ls": -0.05,
        "wt": 400,
        "align": "c",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       },
       {
        "k": "img",
        "id": "688:178",
        "x": 454,
        "y": 1384,
        "w": 371,
        "h": 380,
        "src": "/images/figma/79695ed7de79fc8ff6acf20af350c1d7445181f9.webp",
        "alt": "Tay ông đặt cạnh tay cháu Thế hệ trước đi cạnh thế hệ sau Màu máu đỏ đi liền với hình sao vàng",
        "crop": [
         [
          1,
          0,
          0
         ],
         [
          0,
          0.5761,
          0.344
         ]
        ]
       },
       {
        "k": "text",
        "id": "685:171",
        "x": 356,
        "y": 1801,
        "w": 576,
        "h": 144,
        "text": "Gia đình và đất nước, mối liên hệ gần gũi luôn tồn tại trong mỗi cá nhân. Có mình, có gia đình, có đất nước, tầng tầng lớp lớp, giữ gìn và tiếp nối.\n\nTết Độc Lập 2/9, cùng Tíc Cơ nhìn lại những điều tưởng chừng nhỏ bé trong đời sống, trân trọng những giá trị thực gắn kết và bảo vệ những giá trị vẹn nguyên của dân tộc.",
        "size": 18,
        "lh": 1.33,
        "ls": -0.05,
        "wt": 300,
        "align": "l",
        "color": "#ffffff",
        "tag": "p"
       }
      ]
     },
     {
      "k": "text",
      "id": "692:180",
      "x": 198,
      "y": 2099,
      "w": 883,
      "h": 168,
      "text": "Gia đình là hạt nhân của đất nước, đất nước thành hình từ nhiều gia đình, kết nối và gắn kết.\n\nCùng nghe chúng tôi kể về những thế hệ thành viên trong một gia đình, hạt nhân tạo nên một đất nước vững chãi và bền bỉ!",
      "size": 24,
      "lh": 1.17,
      "ls": -0.05,
      "wt": 300,
      "align": "l",
      "color": "#ffffff",
      "tag": "p"
     },
     {
      "k": "card",
      "id": "735:173",
      "items": [
       {
        "k": "img",
        "id": "692:182",
        "x": 198,
        "y": 2290,
        "w": 282,
        "h": 282,
        "src": "/images/figma/0f77611a21fd3a3eecf814e57b06fe2a32fcb652.webp",
        "alt": "Đọc thêm về em bé của đất nước"
       },
       {
        "k": "text",
        "id": "692:185",
        "x": 240,
        "y": 2602,
        "w": 198,
        "h": 32,
        "text": "Đọc thêm về\nem bé của đất nước",
        "size": 14,
        "lh": 1.14,
        "ls": -0.05,
        "wt": 300,
        "align": "c",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       }
      ],
      "href": "https://www.instagram.com/p/C_QXPIePuEk/?img_index=1"
     },
     {
      "k": "card",
      "id": "735:174",
      "items": [
       {
        "k": "img",
        "id": "692:184",
        "x": 499,
        "y": 2292,
        "w": 281,
        "h": 281,
        "src": "/images/figma/cec9ead0178001d8090cd49f4156d2768ed68c4e.webp",
        "alt": "Đọc thêm về người phụ nữ thế hệ giao thời"
       },
       {
        "k": "text",
        "id": "692:187",
        "x": 541,
        "y": 2602,
        "w": 198,
        "h": 32,
        "text": "Đọc thêm về\nngười phụ nữ thế hệ giao thời",
        "size": 14,
        "lh": 1.14,
        "ls": -0.05,
        "wt": 300,
        "align": "c",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       }
      ],
      "href": "https://www.instagram.com/p/C_Vh3yZPY3L/?img_index=1"
     },
     {
      "k": "card",
      "id": "735:175",
      "items": [
       {
        "k": "img",
        "id": "692:183",
        "x": 799,
        "y": 2293,
        "w": 282,
        "h": 282,
        "src": "/images/figma/722c2997149cf9235d731d76366e7dac46e3cd0b.webp",
        "alt": "Đọc thêm về người ông cựu chiến binh"
       },
       {
        "k": "text",
        "id": "692:189",
        "x": 841,
        "y": 2599,
        "w": 198,
        "h": 32,
        "text": "Đọc thêm về\nngười ông cựu chiến binh",
        "size": 14,
        "lh": 1.14,
        "ls": -0.05,
        "wt": 300,
        "align": "c",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       }
      ],
      "href": "https://www.instagram.com/p/C_Vh3yZPY3L/?img_index=1"
     }
    ],
    "bg": "#b51515"
   }
  ]
 },
 "freezedom-thu-roi-nghi-di": {
  "h": 6148,
  "sections": [
   {
    "id": "694:50",
    "y": 0,
    "items": [
     {
      "k": "box",
      "id": "694:51",
      "x": 0,
      "y": 0,
      "w": 1280,
      "h": 524,
      "bg": "#ac8bc3"
     },
     {
      "k": "text",
      "id": "694:52",
      "x": 62,
      "y": 84,
      "w": 772,
      "h": 248,
      "text": "Thu Rồi\nNghỉ Đi",
      "size": 135,
      "lh": 0.92,
      "ls": -0.08,
      "wt": 400,
      "align": "l",
      "color": "#ffffff",
      "tag": "h1",
      "nowrap": true
     },
     {
      "k": "text",
      "id": "694:75",
      "x": 475,
      "y": 255,
      "w": 216,
      "h": 101,
      "text": "vol.1",
      "size": 40,
      "lh": 2.53,
      "ls": -0.08,
      "wt": 400,
      "align": "l",
      "color": "#ffffff",
      "tag": "h2",
      "nowrap": true
     },
     {
      "k": "text",
      "id": "732:23",
      "x": 345,
      "y": 239,
      "w": 874,
      "h": 136,
      "text": "Tíc Cơ\n& Freezedom",
      "size": 80,
      "lh": 0.85,
      "ls": -0.08,
      "wt": 400,
      "align": "r",
      "color": "#ffffff",
      "tag": "h2",
      "nowrap": true
     },
     {
      "k": "text",
      "id": "694:53",
      "x": 834,
      "y": 382,
      "w": 385,
      "h": 56,
      "text": "bắt tay nghỉ ngơi vào\nnhững ngày thu 2025!",
      "size": 24,
      "lh": 1.17,
      "ls": -0.05,
      "wt": 400,
      "align": "r",
      "color": "#ffffff",
      "tag": "p",
      "nowrap": true
     }
    ],
    "bg": "#ac8bc3"
   },
   {
    "id": "728:18",
    "y": 524,
    "items": [
     {
      "k": "img",
      "id": "728:18",
      "x": 0,
      "y": 524,
      "w": 1280,
      "h": 762,
      "src": "/images/figma/27c9fdfd3cecd2d131b53ae50fe1bb7864074c02.webp",
      "alt": "Tíc Cơ x Freezedom: Thu Rồi Nghỉ Đi",
      "crop": [
       [
        0.9983,
        0,
        0.0009
       ],
       [
        0,
        0.3962,
        0.5486
       ]
      ]
     }
    ]
   },
   {
    "id": "735:182",
    "y": 1286,
    "items": [
     {
      "k": "box",
      "id": "732:25",
      "x": 0,
      "y": 1286,
      "w": 1280,
      "h": 1266,
      "bg": "#ac8bc3"
     },
     {
      "k": "card",
      "id": "735:178",
      "items": [
       {
        "k": "text",
        "id": "732:27",
        "x": 227,
        "y": 1375,
        "w": 825,
        "h": 56,
        "text": "Nếu bạn có vô tình thấy event \"Hà Nội mùa thu, bị ngu mới đi làm\"\nđâu đó trên Facebook, thì đó chính là Tíc Cơ và Freezedom vào mùa thu 2025!",
        "size": 24,
        "lh": 1.17,
        "ls": -0.05,
        "wt": 400,
        "align": "c",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       },
       {
        "k": "img",
        "id": "732:30",
        "x": 313,
        "y": 1457,
        "w": 653,
        "h": 257,
        "src": "/images/figma/90166f36f2b069b8cd9b18ce0ba854c532e63cd9.webp",
        "alt": "Nếu bạn có vô tình thấy event \"Hà Nội mùa thu, bị ngu mới đi làm\" đâu đó trên Facebook, thì đó chính là Tíc Cơ và Freezedom vào mùa thu 2025!"
       }
      ]
     },
     {
      "k": "text",
      "id": "732:32",
      "x": 95,
      "y": 1785,
      "w": 707,
      "h": 160,
      "text": "Làm nhiều thì dễ mệt, mệt nhiều thì nghỉ đi. Nhân những ngày đương vào thu đẹp trời, chúng tôi cùng Freezedom quyết định tắt tạm lap và nghỉ ngơi hưởng mùa thu Hà Nội.",
      "size": 36,
      "lh": 1.11,
      "ls": -0.05,
      "wt": 400,
      "align": "l",
      "color": "#ffffff",
      "tag": "h2"
     },
     {
      "k": "text",
      "id": "732:39",
      "x": 95,
      "y": 2034,
      "w": 745,
      "h": 80,
      "text": "Sản phẩm collab:\nHộp quà Nghỉ Đi",
      "size": 45,
      "lh": 0.89,
      "ls": -0.05,
      "wt": 500,
      "align": "l",
      "color": "#270350",
      "tag": "h2",
      "nowrap": true
     },
     {
      "k": "text",
      "id": "732:34",
      "x": 95,
      "y": 2190,
      "w": 507,
      "h": 224,
      "text": "Và thế là hộp quà Nghỉ Đi được ra đời\nHộp bao gồm 01 sổ tay Nghỉ Đi từ Tíc Cơ\nvà 02 hộp kem trong collection Thu Rồi\nmới toanh từ Freezedom.\n\nSự kết hợp ngẫu hứng mà hợp lý để bạn nghỉ ngơi lấy sức, ăn kem viết sổ, nghỉ ngơi lấy đà để còn có sức chạy xa!",
      "size": 24,
      "lh": 1.17,
      "ls": -0.05,
      "wt": 400,
      "align": "l",
      "color": "#ffffff",
      "tag": "p",
      "mark": "#270350",
      "markParts": [
       "01 sổ tay Nghỉ Đi từ Tíc Cơ",
       "02 hộp kem trong collection Thu Rồi",
       "từ Freezedom."
      ]
     },
     {
      "k": "card",
      "id": "735:179",
      "items": [
       {
        "k": "img",
        "id": "732:37",
        "x": 769,
        "y": 2034,
        "w": 408,
        "h": 380,
        "src": "/images/figma/0b1668305e236e8f34889afd1d929495dd6fb563.webp",
        "alt": "Xem thêm về hộp quà Nghỉ Đi",
        "crop": [
         [
          0.889,
          0,
          0.0495
         ],
         [
          0,
          0.5519,
          0.3387
         ]
        ]
       },
       {
        "k": "text",
        "id": "732:41",
        "x": 874,
        "y": 2440,
        "w": 198,
        "h": 44,
        "text": "Xem thêm về\nhộp quà Nghỉ Đi",
        "size": 20,
        "lh": 1.1,
        "ls": -0.05,
        "wt": 300,
        "align": "c",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       }
      ],
      "href": "/san-pham/so-nghi-di"
     }
    ],
    "bg": "#ac8bc3"
   },
   {
    "id": "735:183",
    "y": 2526,
    "items": [
     {
      "k": "img",
      "id": "732:44",
      "x": -89,
      "y": 2526,
      "w": 718,
      "h": 596,
      "src": "/images/figma/3ad8773684a4d91ec3af7377a02f9bfd6d7304f2.webp",
      "alt": "Tíc Cơ x Freezedom: Thu Rồi Nghỉ Đi",
      "crop": [
       [
        0.9609,
        0,
        0.0001
       ],
       [
        0,
        0.5317,
        0.2986
       ]
      ]
     },
     {
      "k": "img",
      "id": "732:46",
      "x": 629,
      "y": 2526,
      "w": 663,
      "h": 596,
      "src": "/images/figma/3c59ce46ee2ae854b87ba70fe7f6ffc68839a32b.webp",
      "alt": "Tíc Cơ x Freezedom: Thu Rồi Nghỉ Đi",
      "crop": [
       [
        1,
        0,
        0
       ],
       [
        0,
        0.6745,
        0.1885
       ]
      ]
     }
    ]
   },
   {
    "id": "735:190",
    "y": 3122,
    "items": [
     {
      "k": "box",
      "id": "732:47",
      "x": 0,
      "y": 3122,
      "w": 1280,
      "h": 2219,
      "bg": "#ac8bc3"
     },
     {
      "k": "card",
      "id": "735:184",
      "items": [
       {
        "k": "text",
        "id": "732:49",
        "x": 95,
        "y": 3214,
        "w": 745,
        "h": 40,
        "text": "Nhưng như thế là chưa đủ!",
        "size": 36,
        "lh": 1.11,
        "ls": -0.05,
        "wt": 400,
        "align": "l",
        "color": "#ffffff",
        "tag": "h2",
        "nowrap": true
       },
       {
        "k": "text",
        "id": "732:52",
        "x": 95,
        "y": 3254,
        "w": 652,
        "h": 28,
        "text": "Chúng tôi nghĩ cần phải một cuộc tụ họp trực tiếp ngoài đời",
        "size": 24,
        "lh": 1.17,
        "ls": -0.05,
        "wt": 400,
        "align": "l",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       },
       {
        "k": "text",
        "id": "735:64",
        "x": 268,
        "y": 3373,
        "w": 745,
        "h": 40,
        "text": "Pop-up Event Thu Rồi Nghỉ Đi",
        "size": 45,
        "lh": 0.89,
        "ls": -0.05,
        "wt": 500,
        "align": "c",
        "color": "#270350",
        "tag": "h2",
        "nowrap": true
       },
       {
        "k": "text",
        "id": "735:66",
        "x": 565,
        "y": 3412,
        "w": 151,
        "h": 40,
        "text": "được ra đời!",
        "size": 24,
        "lh": 1.67,
        "ls": -0.05,
        "wt": 500,
        "align": "c",
        "color": "#270350",
        "tag": "p",
        "nowrap": true
       },
       {
        "k": "img",
        "id": "735:68",
        "x": 0,
        "y": 3475,
        "w": 1280,
        "h": 571,
        "src": "/images/figma/06a53dbb08da33457eee373b5d7583be933d9947.webp",
        "alt": "Nhưng như thế là chưa đủ!",
        "crop": [
         [
          1,
          0,
          0
         ],
         [
          0,
          0.7931,
          0.1042
         ]
        ]
       }
      ]
     },
     {
      "k": "text",
      "id": "735:70",
      "x": 95,
      "y": 4108,
      "w": 678,
      "h": 84,
      "text": "Một không gian gặp gỡ, lấy cái cớ để bạn nghỉ đi, hưởng trời thu và chẳng làm gì nhiều ngoài việc thư giãn, ăn kem, viết sổ và tỉ tê trò chuyện dưới nắng gió nhè nhẹ mùa thu",
      "size": 24,
      "lh": 1.17,
      "ls": -0.05,
      "wt": 400,
      "align": "l",
      "color": "#ffffff",
      "tag": "p"
     },
     {
      "k": "card",
      "id": "735:186",
      "items": [
       {
        "k": "img",
        "id": "735:72",
        "x": 0,
        "y": 4239,
        "w": 517,
        "h": 645,
        "src": "/images/figma/540148cd27ae86dce7a8bbd0130b93f0f5d60334.webp",
        "alt": "ăn kem",
        "crop": [
         [
          0.9992,
          0,
          0.0004
         ],
         [
          0,
          0.7007,
          0.2299
         ]
        ]
       },
       {
        "k": "text",
        "id": "735:82",
        "x": 525,
        "y": 4239,
        "w": 87,
        "h": 70,
        "text": "ăn\nkem",
        "size": 45,
        "lh": 0.78,
        "ls": -0.05,
        "wt": 500,
        "align": "l",
        "color": "#ffffff",
        "tag": "h2",
        "nowrap": true
       }
      ]
     },
     {
      "k": "card",
      "id": "735:187",
      "items": [
       {
        "k": "text",
        "id": "735:83",
        "x": 570,
        "y": 4761,
        "w": 185,
        "h": 76,
        "text": "mua sắm\nTíc Cơ",
        "size": 45,
        "lh": 0.84,
        "ls": -0.05,
        "wt": 500,
        "align": "r",
        "color": "#ffffff",
        "tag": "h2",
        "nowrap": true
       },
       {
        "k": "img",
        "id": "735:76",
        "x": 763,
        "y": 4239,
        "w": 518,
        "h": 598,
        "src": "/images/figma/8a0a62360b1418dd83cf79021140c7690bb7e9bf.webp",
        "alt": "mua sắm Tíc Cơ",
        "crop": [
         [
          0.9172,
          0,
          0.0285
         ],
         [
          0,
          0.5967,
          0.2318
         ]
        ]
       }
      ]
     },
     {
      "k": "card",
      "id": "735:188",
      "items": [
       {
        "k": "img",
        "id": "735:78",
        "x": 773,
        "y": 4856,
        "w": 507,
        "h": 413,
        "src": "/images/figma/fcf010d8bab4be704614cdc117ff0c41cae7ce29.webp",
        "alt": "tỉ tê trò chuyện",
        "crop": [
         [
          0.9984,
          0,
          0.0008
         ],
         [
          0,
          0.4572,
          0.4363
         ]
        ]
       },
       {
        "k": "text",
        "id": "735:85",
        "x": 624,
        "y": 4872,
        "w": 215,
        "h": 78,
        "text": "tỉ tê\ntrò chuyện",
        "size": 45,
        "lh": 0.87,
        "ls": -0.05,
        "wt": 500,
        "align": "l",
        "color": "#ffffff",
        "tag": "h2",
        "nowrap": true
       }
      ]
     },
     {
      "k": "text",
      "id": "735:89",
      "x": 59,
      "y": 5161,
      "w": 678,
      "h": 84,
      "text": "Trong khuôn khổ sự kiện, chúng mình kết hợp với Bludot tổ chức Chợ phiên Mùa Thu Hà Nội với nhiều gian hàng đồ ăn, local arts; Workshop của Lớp học Hồng Xiêm; Vinyl DJ session.",
      "size": 24,
      "lh": 1.17,
      "ls": -0.05,
      "wt": 400,
      "align": "l",
      "color": "#ffffff",
      "tag": "p"
     }
    ],
    "bg": "#ac8bc3",
    "anchor": "pop-up-event"
   },
   {
    "id": "735:189",
    "y": 5341,
    "items": [
     {
      "k": "img",
      "id": "735:91",
      "x": 0,
      "y": 5341,
      "w": 1280,
      "h": 807,
      "src": "/images/figma/68b96ea928c76397848ee071722f4a1e8b4218f5.webp",
      "alt": "Tíc Cơ x Freezedom: Thu Rồi Nghỉ Đi",
      "crop": [
       [
        1,
        0,
        0
       ],
       [
        0,
        0.4203,
        0.4642
       ]
      ]
     },
     {
      "k": "text",
      "id": "735:93",
      "x": 267,
      "y": 5835,
      "w": 745,
      "h": 40,
      "text": "giữ sức - nghỉ đi - hưởng thu!",
      "size": 45,
      "lh": 0.89,
      "ls": -0.05,
      "wt": 500,
      "align": "c",
      "color": "#ffffff",
      "tag": "h2",
      "nowrap": true
     }
    ]
   }
  ]
 },
 "neenee-dau-doi-mu-chan-vao-doi": {
  "h": 2571,
  "sections": [
   {
    "id": "735:212",
    "y": 0,
    "items": [
     {
      "k": "box",
      "id": "735:213",
      "x": 0,
      "y": 0,
      "w": 1280,
      "h": 524,
      "bg": "#2c4425"
     },
     {
      "k": "text",
      "id": "735:214",
      "x": 62,
      "y": 128,
      "w": 772,
      "h": 190,
      "text": "Đầu đội mũ,\nChân vào đời",
      "size": 100,
      "lh": 0.95,
      "ls": -0.08,
      "wt": 400,
      "align": "l",
      "color": "#ffffff",
      "tag": "h1",
      "nowrap": true
     },
     {
      "k": "text",
      "id": "735:216",
      "x": 345,
      "y": 239,
      "w": 874,
      "h": 136,
      "text": "Tíc Cơ\n& Neenee",
      "size": 80,
      "lh": 0.85,
      "ls": -0.08,
      "wt": 400,
      "align": "r",
      "color": "#ffffff",
      "tag": "h2",
      "nowrap": true
     },
     {
      "k": "text",
      "id": "735:217",
      "x": 834,
      "y": 382,
      "w": 385,
      "h": 56,
      "text": "dự án hợp tác sản phẩm\ngiữa Neenee và Tíc Cơ!",
      "size": 24,
      "lh": 1.17,
      "ls": -0.05,
      "wt": 400,
      "align": "r",
      "color": "#ffffff",
      "tag": "p",
      "nowrap": true
     }
    ],
    "bg": "#2c4425"
   },
   {
    "id": "735:218",
    "y": 524,
    "items": [
     {
      "k": "img",
      "id": "735:218",
      "x": 0,
      "y": 524,
      "w": 1280,
      "h": 614,
      "src": "/images/figma/f2cf54a35f7450b5c8064f681e3305bf3ab43488.webp",
      "alt": "Tíc Cơ x Neenee: Đầu đội mũ, Chân vào đời",
      "crop": [
       [
        0.7346,
        0,
        0.1192
       ],
       [
        0,
        0.2643,
        0.4103
       ]
      ]
     }
    ]
   },
   {
    "id": "735:302",
    "y": 1138,
    "items": [
     {
      "k": "box",
      "id": "735:266",
      "x": 0,
      "y": 1138,
      "w": 1280,
      "h": 1433,
      "bg": "#2c4425"
     },
     {
      "k": "card",
      "id": "735:298",
      "items": [
       {
        "k": "text",
        "id": "735:268",
        "x": 274,
        "y": 1213,
        "w": 731,
        "h": 84,
        "text": "Không có mũ cũng được, nhưng có thì còn vui hơn\nBiến mấy thứ mình đội hàng ngày thêm màu sắc và vào mood\nĐầu đội mũ nâng cao tinh thần, chân cứ thế mà hoan hỷ nhảy vào đời!",
        "size": 24,
        "lh": 1.17,
        "ls": -0.05,
        "wt": 400,
        "align": "c",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       },
       {
        "k": "img",
        "id": "735:271",
        "x": 412,
        "y": 1348,
        "w": 456,
        "h": 355,
        "src": "/images/figma/35c539974241fe4fcc0ff878739d8c9468cd03a1.webp",
        "alt": "Không có mũ cũng được, nhưng có thì còn vui hơn Biến mấy thứ mình đội hàng ngày thêm màu sắc và vào mood Đầu đội mũ nâng cao tinh thần, chân cứ thế mà hoan hỷ nhảy vào đời!",
        "crop": [
         [
          1.0031,
          0,
          0
         ],
         [
          0,
          0.5859,
          0.1859
         ]
        ]
       }
      ]
     },
     {
      "k": "text",
      "id": "735:273",
      "x": 62,
      "y": 1754,
      "w": 651,
      "h": 171,
      "text": "02 mẫu mũ\nchúng tôi hợp tác\ncho ra mắt!",
      "size": 60,
      "lh": 0.95,
      "ls": -0.08,
      "wt": 400,
      "align": "l",
      "color": "#ffffff",
      "tag": "h2",
      "nowrap": true
     },
     {
      "k": "card",
      "id": "735:299",
      "items": [
       {
        "k": "img",
        "id": "735:277",
        "x": 274,
        "y": 1962,
        "w": 275,
        "h": 366,
        "src": "/images/figma/14341c1b98597c12ac27da8ad8e345dbc4a14bb1.webp",
        "alt": "Mũ lưỡi trai Chả Sao",
        "crop": [
         [
          0.6724,
          0,
          0.1638
         ],
         [
          0,
          0.6711,
          0.1644
         ]
        ]
       },
       {
        "k": "text",
        "id": "735:280",
        "x": 274,
        "y": 2347,
        "w": 211,
        "h": 28,
        "text": "Mũ lưỡi trai Chả Sao",
        "size": 24,
        "lh": 1.17,
        "ls": -0.05,
        "wt": 400,
        "align": "c",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       },
       {
        "k": "text",
        "id": "735:282",
        "x": 274,
        "y": 2403,
        "w": 275,
        "h": 63,
        "text": "nghĩ sao thì đời vậy, nghĩ chả sao thì chả phải sợ! đội mũ chả sao, mãi tinh thần chả sao!",
        "size": 18,
        "lh": 1.17,
        "ls": -0.05,
        "wt": 300,
        "align": "l",
        "color": "#ffffff",
        "tag": "p",
        "op": 0.77
       },
       {
        "k": "text",
        "id": "735:287",
        "x": 155,
        "y": 2128,
        "w": 119,
        "h": 63,
        "text": "> xem thêm\nvề mũ lưỡi trai\nChả Sao",
        "size": 18,
        "lh": 1.17,
        "ls": -0.05,
        "wt": 300,
        "align": "l",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       }
      ],
      "href": "/san-pham/bst-dau-doi-mu-chan-vao-doi"
     },
     {
      "k": "card",
      "id": "735:300",
      "items": [
       {
        "k": "img",
        "id": "735:278",
        "x": 731,
        "y": 1962,
        "w": 274,
        "h": 366,
        "src": "/images/figma/2c653a28c511fd498a049a49c20053b94ea7fa3a.webp",
        "alt": "Mũ tai bèo Ha Ha",
        "crop": [
         [
          0.5747,
          0,
          0.2751
         ],
         [
          0,
          0.5758,
          0.2537
         ]
        ]
       },
       {
        "k": "text",
        "id": "735:284",
        "x": 731,
        "y": 2347,
        "w": 181,
        "h": 28,
        "text": "Mũ tai bèo Ha Ha",
        "size": 24,
        "lh": 1.17,
        "ls": -0.05,
        "wt": 400,
        "align": "c",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       },
       {
        "k": "text",
        "id": "735:285",
        "x": 731,
        "y": 2403,
        "w": 275,
        "h": 63,
        "text": "bạn haha, đời nở hoa\nmiệng ngân nga, mũ tô điểm vào một ngày âm u!",
        "size": 18,
        "lh": 1.17,
        "ls": -0.05,
        "wt": 300,
        "align": "l",
        "color": "#ffffff",
        "tag": "p",
        "op": 0.77
       },
       {
        "k": "text",
        "id": "735:289",
        "x": 1003,
        "y": 2128,
        "w": 119,
        "h": 63,
        "text": "> xem thêm\nvề mũ tai bèo\nHa Ha",
        "size": 18,
        "lh": 1.17,
        "ls": -0.05,
        "wt": 300,
        "align": "r",
        "color": "#ffffff",
        "tag": "p",
        "nowrap": true
       }
      ],
      "href": "/san-pham/bst-dau-doi-mu-chan-vao-doi"
     }
    ],
    "bg": "#2c4425"
   }
  ]
 }
};
